#Hystrix Turbine Server
server:
  port: 9010

spring:
  application:
    name: msa-turbine-server

#Eureka Client   
eureka:
  instance:
    prefer-ip-address: true         #HostName이 IP 에 의존하여 설정
  client:
    registerWithEureka: true       #자체 서비스를 eureka 서버에 등록 할지 여부
    fetchRegistry: true            #client 서비스가 eureka 서버로 부터 서비스 리스트 정보를 local에 caching 할지 여부
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    
turbine:
  appConfig: msa-svc-member,msa-svc-order,msa-zuul-server
  clusterNameExpression: new String("default")      
  
 #Stream URL : http://msa-turbine-server:9010/turbine.stream
