apiVersion: v1
kind: Service
metadata:
  labels:
    run: msa-config-server
  name: msa-config-server
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    run: msa-config-server
  type: ClusterIP
