apiVersion: v1
kind: Service
metadata:
  labels:
    run: msa-zuul-server
  name: msa-zuul-server
spec:
  ports:
  - port: 9090
    #protocol: TCP
    targetPort: 9090
  selector:
    run: msa-zuul-server
  type: ClusterIP


