apiVersion: v1
kind: Service
metadata:
  labels:
    run: msa-svc-order
  name: msa-svc-order
spec:
  ports:
  - port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    run: msa-svc-order
  type: ClusterIP


