apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq2
  labels:
    app: rabbitmq2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq2
  template:
    metadata:
      labels:
        app: rabbitmq2
    spec:
      containers:
      - name: rabbitmq2
        image: 192.168.100.102:5000/msasmp01/rabbitmq:3-management
        ports:
          - name: http
            protocol: TCP
            containerPort: 15672
          - name: amqp
            protocol: TCP
            containerPort: 5672
        env:
        - name: "RABBITMQ_ERLANG_COOKIE"
          value: "1WqgH8N2v1qDBDZDbNy8Bg9IkPWLEpu79m6q+0t36lQ="
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-data
      nodeSelector:
        kubernetes.io/hostname: worker3
      volumes:
        - name: rabbitmq-data
          hostPath:
            path: /sw/rabbitmq/data
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq2
  labels:
    app: rabbitmq2
spec:
  clusterIP: None
  ports:           
   - name: http    
     protocol: TCP 
     port: 15672
     targetPort: 15672
   - name: amqp
     protocol: TCP
     port: 5672
     targetPort: 5672
  selector:
    app: rabbitmq2
---
apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: rabbitmq2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: rabbitmq2.msasmp01.com
    http:
      paths:
      - path: /
        backend:
          serviceName: rabbitmq2
          servicePort: 15672

