server:
  port: 9091

spring:
  application:
    name: msa-svc-member
  sleuth:
    sampler:
      probability: 0.1    #얼마나 많은 비율로 zipkin에 송신하는 transaction 비율(Default 0.1(10%), 설정 1.0(100%))
  zipkin:
    base-url: http://msa-zipkin-server:9411 #ZipKin Server      

#  data:
#    mongodb:
#      host: mongodb-standalone-0.mongodb
#      username: user
#      password: password
#      database: sample01
#      port: 27017

  datasource:
#    initialization-mode: always #Schema.sql 실행을 위해 설정
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mylab-mariadb:3306/mylab01?characterEncoding=UTF-8&serverTimezone=UTC
    username: mylab01
    password: abcd1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    generate-ddl: false  #최초 데이터베이스 스키마를 자동으로 생성(개발환경에서 주로 사용)
    hibernate:
      format_sql: true  #쿼리문을 가독성 있게 출력
      ddl-auto: validate    #명시적인 Schema.sql 등을 사용시에는 turn-off 설정(none 또는 validate)

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE  #쿼리문의 바인드 파라미터 출력      
            
#Eureka Client   
eureka:
  instance:
    prefer-ip-address: true         #HostName이 IP 에 의존하여 설정
  client:
    registerWithEureka: true       #자체 서비스를 eureka 서버에 등록 할지 여부
    fetchRegistry: true            #client 서비스가 eureka 서버로 부터 서비스 리스트 정보를 local에 caching 할지 여부
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://msa-eureka-server:8761/eureka/

feign:
  client:
    config:
      default:                  # or feign name
        connectTimeout: 5000    # Client에서 서버로 요청시 서버와의 Connection 맺기 까지의 delay time
        readTimeout: 5000       # Connection 맺은 후 response 받기 까지 delay time

#turbine 수집을 위한 endpoint 활성화        
management:
  endpoints:
    web:
      exposure:
        include: "*"     

springfox:
  documentation:
    swagger:
      v2:
        path: /v1/member/api-docs        
