server:
  port: 9080
  
spring:
  application:
    name: msa-auth-server
    
  datasource:
    initialization-mode: always #Schema.sql 실행을 위해 설정
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mylab-mariadb:3306/mylab01?characterEncoding=UTF-8&serverTimezone=UTC
    username: mylab01
    password: abcd1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    generate-ddl: false  #최초 데이터베이스 스키마를 자동으로 생성(개발환경에서 주로 사용)
    hibernate:
      format_sql: true  #쿼리문을 가독성 있게 출력
      ddl-auto: validate    #명시적인 Schema.sql 등을 사용시에는 turn-off 설정(none 또는 validate)
      
#Eureka Client   
eureka:
  instance:
    prefer-ip-address: true         #HostName이 IP 에 의존하여 설정
  client:
    registerWithEureka: true       #자체 서비스를 eureka 서버에 등록 할지 여부
    fetchRegistry: true            #client 서비스가 eureka 서버로 부터 서비스 리스트 정보를 local에 caching 할지 여부
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://msa-eureka-server:8761/eureka/

signing.key: "345345fsdgsf5345"

security:
  oauth2:
    resource:
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt4w9qdhOB0+J2zhUG6AE
          uyr1vEUHSATWwKpwQ5xc0+7rPCLXibjbCAO+AWbA/JHZ29XTIerdufDJEdux+JJc
          phljNXWz/FGuMSdU9EzsBVimMbthYwVrlmj1iaSsNfR4Vl1qA6WqACmjsjEoPEcE
          75AefArOF0LLKJ3jsDs/MJ4t+bd2F3so3IWE1FtOhBGUWWfgnIXpfpj1i+FCEcQt
          41R6YH8hvyJHRh4pW3gcz5uIPvZT3l/4MRGr9LNDpoq2nIxvynnLl/KsTgnm+6Lm
          V1G4DsdbPCxSR4ywKkiSp+5z69pF4DFbNqesUNpJtwqXTb2QEkiQSnx9UaDkZT23
          SwIDAQAB
          -----END PUBLIC KEY-----