apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: msa-svc-member
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: msa-svc-member
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30