apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: msa-zuul-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: msa-zuul-server
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 30