apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    run: msa-zipkin-server
  name: msa-zipkin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: msa-zipkin-server
  template:
    metadata:
      labels:
        run: msa-zipkin-server
    spec:
      containers:
      - image: 192.168.100.102:5000/msasmp01/msa-zipkin-server:1.0
        imagePullPolicy: Always
        name: msa-zipkin-server
        ports:
        - containerPort: 9411
          protocol: TCP
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: msa-zipkin-server
  name: msa-zipkin-server
spec:
  ports:
  - port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    run: msa-zipkin-server
  type: ClusterIP


---
apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: msa-zipkin-server
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: zipkin.msasmp01.com
    http:
      paths:
      - path: /
        backend:
          serviceName: msa-zipkin-server
          servicePort: 9411
